name: Brian Smith, Wonderboy
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
url: http://bsmitty5000.github.io
